### ISSUE TITLE
The base SlashCommand cannot be instantiated

### ISSUE THREAD

**Issue by kenrad24** [Androz2091/discord-music-bot#1]
## Cannot run the program after pulling from git and doing the initial setup.

**Running on Linode VM**
**Node.js v14.17.5**
**Ubuntu 21.04**

I pulled down the repo from git, setup the .env file as required, and ran the npm install command.

### Installed the lib dependencies.

```cwatson@localhost:~/discord-music-bot$ npm install

> @discordjs/opus@0.6.0 install /home/cwatson/discord-music-bot/node_modules/@discordjs/opus
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v83-napi-v3-linux-x64-glibc-2.33.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.6.0 and node@14.17.5 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v83-napi-v3-linux-x64-glibc-2.33.tar.gz
make: Entering directory '/home/cwatson/discord-music-bot/node_modules/@discordjs/opus/build'
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_projection_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/analysis.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mlp_data.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_projection_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mapping_matrix.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_compare.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mlp.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/repacketizer.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_frame.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/inner_product_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/scale_vector_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_pred_coefs_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/schur_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/warped_autocorrelation_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/burg_modified_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_LPC_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LPC_inv_pred_gain_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/scale_copy_vector_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/noise_shape_analysis_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/pitch_analysis_core_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/bwexpander_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LTP_analysis_filter_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LTP_scale_ctrl_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/corrMatrix_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/encode_frame_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/sort_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_pitch_lags_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/residual_energy_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LPC_analysis_filter_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/autocorrelation_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/k2a_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/regularize_correlations_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_LTP_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/energy_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/apply_sine_window_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/wrappers_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/process_gains_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_quant_pred.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LPC_inv_pred_gain.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/process_NLSFs.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NSQ.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/check_control_input.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_del_dec_quant.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LPC_analysis_filter.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/dec_API.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/sort.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/VAD.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_AR2.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LPC_fit.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/control_SNR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_parameters.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/pitch_est_tables.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/warped_autocorrelation_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/apply_sine_window_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/residual_energy16_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/schur64_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/residual_energy_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/noise_shape_analysis_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/encode_frame_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/schur_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/autocorr_FIX.o
../deps/opus/silk/fixed/autocorr_FIX.c: In function ‘silk_autocorr’:
../deps/opus/silk/fixed/autocorr_FIX.c:47:29: warning: passing argument 1 of ‘_celt_autocorr’ from incompatible pointer type [-Wincompatible-pointer-types]
   47 |     *scale = _celt_autocorr(inputData, results, NULL, 0, corrCount-1, inputDataSize, arch);
      |                             ^~~~~~~~~
      |                             |
      |                             const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/autocorr_FIX.c:33:
../deps/opus/celt/celt_lpc.h:63:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
   63 | int _celt_autocorr(const opus_val16 *x, opus_val32 *ac,
      |                    ~~~~~~~~~~~~~~~~~~^
../deps/opus/silk/fixed/autocorr_FIX.c:47:40: warning: passing argument 2 of ‘_celt_autocorr’ from incompatible pointer type [-Wincompatible-pointer-types]
   47 |     *scale = _celt_autocorr(inputData, results, NULL, 0, corrCount-1, inputDataSize, arch);
      |                                        ^~~~~~~
      |                                        |
      |                                        opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/autocorr_FIX.c:33:
../deps/opus/celt/celt_lpc.h:63:53: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
   63 | int _celt_autocorr(const opus_val16 *x, opus_val32 *ac,
      |                                         ~~~~~~~~~~~~^~
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/burg_modified_FIX.o
../deps/opus/silk/fixed/burg_modified_FIX.c: In function ‘silk_burg_modified_c’:
../deps/opus/silk/fixed/burg_modified_FIX.c:98:30: warning: passing argument 1 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
   98 |             celt_pitch_xcorr(x_ptr, x_ptr + 1, xcorr, subfr_length - D, D, arch );
      |                              ^~~~~
      |                              |
      |                              const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/burg_modified_FIX.c:35:
../deps/opus/celt/pitch.h:185:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                    ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/burg_modified_FIX.c:98:43: warning: passing argument 2 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
   98 |             celt_pitch_xcorr(x_ptr, x_ptr + 1, xcorr, subfr_length - D, D, arch );
      |                                     ~~~~~~^~~
      |                                           |
      |                                           const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/burg_modified_FIX.c:35:
../deps/opus/celt/pitch.h:185:60: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                                          ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/burg_modified_FIX.c:98:48: warning: passing argument 3 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
   98 |             celt_pitch_xcorr(x_ptr, x_ptr + 1, xcorr, subfr_length - D, D, arch );
      |                                                ^~~~~
      |                                                |
      |                                                opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/burg_modified_FIX.c:35:
../deps/opus/celt/pitch.h:186:19: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
  186 |       opus_val32 *xcorr, int len, int max_pitch, int arch);
      |       ~~~~~~~~~~~~^~~~~
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/pitch_analysis_core_FIX.o
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c: In function ‘silk_pitch_analysis_core’:
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:200:27: warning: passing argument 1 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  200 |         celt_pitch_xcorr( target_ptr, target_ptr - MAX_LAG_4KHZ, xcorr32, SF_LENGTH_8KHZ, MAX_LAG_4KHZ - MIN_LAG_4KHZ + 1, arch );
      |                           ^~~~~~~~~~
      |                           |
      |                           const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                    ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:200:50: warning: passing argument 2 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  200 |         celt_pitch_xcorr( target_ptr, target_ptr - MAX_LAG_4KHZ, xcorr32, SF_LENGTH_8KHZ, MAX_LAG_4KHZ - MIN_LAG_4KHZ + 1, arch );
      |                                                  ^
      |                                                  |
      |                                                  const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:60: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                                          ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:200:66: warning: passing argument 3 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  200 |         celt_pitch_xcorr( target_ptr, target_ptr - MAX_LAG_4KHZ, xcorr32, SF_LENGTH_8KHZ, MAX_LAG_4KHZ - MIN_LAG_4KHZ + 1, arch );
      |                                                                  ^~~~~~~
      |                                                                  |
      |                                                                  opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:186:19: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
  186 |       opus_val32 *xcorr, int len, int max_pitch, int arch);
      |       ~~~~~~~~~~~~^~~~~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c: In function ‘silk_P_Ana_calc_corr_st3’:
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:616:27: warning: passing argument 1 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  616 |         celt_pitch_xcorr( target_ptr, target_ptr - start_lag - lag_high, xcorr32, sf_length, lag_high - lag_low + 1, arch );
      |                           ^~~~~~~~~~
      |                           |
      |                           const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                    ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:616:62: warning: passing argument 2 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  616 |         celt_pitch_xcorr( target_ptr, target_ptr - start_lag - lag_high, xcorr32, sf_length, lag_high - lag_low + 1, arch );
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
      |                                                              |
      |                                                              const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:60: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                                          ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:616:74: warning: passing argument 3 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  616 |         celt_pitch_xcorr( target_ptr, target_ptr - start_lag - lag_high, xcorr32, sf_length, lag_high - lag_low + 1, arch );
      |                                                                          ^~~~~~~
      |                                                                          |
      |                                                                          opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:186:19: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
  186 |       opus_val32 *xcorr, int len, int max_pitch, int arch);
      |       ~~~~~~~~~~~~^~~~~
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_LTP_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_LPC_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/corrMatrix_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/k2a_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/LTP_scale_ctrl_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/process_gains_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/k2a_Q16_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/regularize_correlations_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/LTP_analysis_filter_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/vector_ops_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_pitch_lags_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_pred_coefs_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/control_audio_bandwidth.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decoder_set_fs.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_unpack.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/bwexpander.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_rom.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/shell_coder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_pulses.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/bwexpander_32.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_core.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/PLC.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_NLSF_CB_WB.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/table_LSF_cos.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_pulses_per_block.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_gain.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/inner_prod_aligned.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_down2_3.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NSQ_del_dec.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_pitch.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_VQ_weights_laroia.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/interpolate.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/debug.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_other.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LP_variable_cutoff.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_decode.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/encode_pulses.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/control_codec.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_LR_to_MS.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/HP_variable_cutoff.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/encode_indices.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/init_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_encode_pred.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_VQ.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/init_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_IIR_FIR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_up2_HQ.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/sigm_Q15.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/sum_sqr_shift.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_LTP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_down2.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/code_signs.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_NLSF_CB_NB_MB.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/gain_quant.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_pitch_lag.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_stabilize.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_find_predictor.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/A2NLSF.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF2A.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/VQ_WMat_EC.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_encode.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/log2lin.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_decode_pred.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/lin2log.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/CNG.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/enc_API.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/biquad_alt.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/quant_LTP_gains.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_down_FIR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/ana_filt_bank_1.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_MS_to_LR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_indices.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/rate.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/entdec.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/modes.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt_lpc.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/laplace.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/cwrs.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/entcode.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/mdct.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/quant_bands.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/vq.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/bands.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/kiss_fft.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/entenc.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/mathops.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/pitch.o
  AR(target) Release/obj.target/deps/opus.a
  COPY Release/opus.a
  CXX(target) Release/obj.target/opus/src/node-opus.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
../src/node-opus.cc: In member function ‘Napi::Value OpusEncoder::Encode(const Napi::CallbackInfo&)’:
../src/node-opus.cc:103:1: warning: control reaches end of non-void function [-Wreturn-type]
  103 | }
      | ^
../src/node-opus.cc: In member function ‘Napi::Value OpusEncoder::Decode(const Napi::CallbackInfo&)’:
../src/node-opus.cc:134:1: warning: control reaches end of non-void function [-Wreturn-type]
  134 | }
      | ^
  SOLINK_MODULE(target) /home/cwatson/discord-music-bot/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.33/opus.node
  COPY Release/opus.node
make: Leaving directory '/home/cwatson/discord-music-bot/node_modules/@discordjs/opus/build'

> youtube-dl-exec@1.2.4 postinstall /home/cwatson/discord-music-bot/node_modules/youtube-dl-exec
> node scripts/postinstall.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for discord.js@13.1.0: wanted: {"node":">=16.6.0","npm":">=7.0.0"} (current: {"node":"14.17.5","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: discord.js@13.1.0
npm WARN notsup Unsupported engine for @discordjs/builders@0.5.0: wanted: {"node":">=14.0.0","npm":">=7.0.0"} (current: {"node":"14.17.5","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @discordjs/builders@0.5.0

added 295 packages from 344 contributors and audited 295 packages in 59.515s

48 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

### Attempted to start bot
 
```~/discord-music-bot$ node .
/home/cwatson/discord-music-bot/node_modules/slash-create/lib/command.js:21
            throw new Error('The base SlashCommand cannot be instantiated.');
            ^

Error: The base SlashCommand cannot be instantiated.
    at new SlashCommand (/home/cwatson/discord-music-bot/node_modules/slash-create/lib/command.js:21:19)
    at new module.exports (/home/cwatson/discord-music-bot/commands/bassboost.js:5:9)
    at SlashCreator.registerCommand (/home/cwatson/discord-music-bot/node_modules/slash-create/lib/creator.js:64:23)
    at SlashCreator.registerCommands (/home/cwatson/discord-music-bot/node_modules/slash-create/lib/creator.js:105:18)
    at SlashCreator.registerCommandsIn (/home/cwatson/discord-music-bot/node_modules/slash-create/lib/creator.js:132:21)
    at Object.<anonymous> (/home/cwatson/discord-music-bot/index.js:39:6)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)```

**Comment by Fakepng** [comment]
I have the same problem

**Comment by tsukasaroot** [comment]
I had this error with node LTS version, i installed the latest 16.7 and no errors popping anymore.

**Comment by QvixoteRoux** [comment]
apparently you need to upgrade to latest discord.js (v 13.x) and that will force you to update node js to 16.x

Is what I had to do and it worked, now I am stuck somewhere else
