### ISSUE TITLE
an application ID must be defined

### ISSUE THREAD

**Issue by Yuinoshi** [Androz2091/discord-music-bot#50]
not working at starting the bot

`PS C:\Hosting\Bot\discord-music-bot-master\discord-music-bot-master> node .
C:\Hosting\Bot\discord-music-bot-master\discord-music-bot-master\node_modules\slash-create\lib\creator.js:31
            throw new Error('An application ID must be defined!');
            ^

Error: An application ID must be defined!
    at new SlashCreator (C:\Hosting\Bot\discord-music-bot-master\discord-music-bot-master\node_modules\slash-create\lib\creator.js:31:19)
    at Object.<anonymous> (C:\Hosting\Bot\discord-music-bot-master\discord-music-bot-master\index.js:21:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47`

**Comment by Positive2022** [comment]
did u forget to provide client id while deploying slash cmd
