### ISSUE TITLE
Bot does not work anymore when installed fresh

### ISSUE THREAD

**Issue by samusaran** [Androz2091/discord-music-bot#87]
The bot just logs on startup

```
 RangeError [BitFieldInvalid]: Invalid bitfield flag or number: GUILDS.
     at Function.resolve (/home/mordack/discord-music-bot/node_modules/discord.js/src/util/BitField.js:168:11)
     at /home/mordack/discord-music-bot/node_modules/discord.js/src/util/BitField.js:163:54
     at Array.map (<anonymous>)
     at Function.resolve (/home/mordack/discord-music-bot/node_modules/discord.js/src/util/BitField.js:163:40)
     at new BitField (/home/mordack/discord-music-bot/node_modules/discord.js/src/util/BitField.js:33:38)
     at new IntentsBitField (/home/mordack/discord-music-bot/node_modules/discord.js/src/util/IntentsBitField.js:9:1)
     at Client._validateOptions (/home/mordack/discord-music-bot/node_modules/discord.js/src/client/Client.js:491:25)
     at new Client (/home/mordack/discord-music-bot/node_modules/discord.js/src/client/Client.js:78:10)
     at Object.<anonymous> (/home/mordack/discord-music-bot/index.js:11:16)
     at Module._compile (node:internal/modules/cjs/loader:1101:14) {
   code: 'BitFieldInvalid'
 }
```

and does not work anymore. This is after a clean install. It worked before on the same machine.

**Comment by RappyTV** [comment]
cannot reproduce. maybe installed wrong discord.js version?

**Comment by samusaran** [comment]
I've updated the discord-player to v6 that required an higher version of discord.js.

I've fixed it and i plan to send a pull request to the report to update the bot.
